In [2]:
%matplotlib inline

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pymc3 as pm
import scipy as sp
from matplotlib.colors import Normalize, rgb2hex
from matplotlib.patches import Polygon
from matplotlib.ticker import FuncFormatter
from mpl_toolkits.basemap import Basemap

In [6]:
data = pd.read_csv("./data/waitingtimes.csv")

In [7]:
data.head()

,ods_code,provider,cancer,care,total_trt,less62wt,more62wt,wtgrp1,wtgrp2,wtgrp3,...,totstaff_merge,medstaff_merge,_Nurse_HealthVisitors,_STT,_Support_Clinical,_Support_STT,nonmedstaff_merge,ytd_plan,ytd_actual,finance_merge
0,REM,AINTREE UNIVERSITY HOSPITAL NHS FOUNDATION TRUST,Breast,NON-ADMITTED,5.5,5.5,0.0,3.0,2.5,0.0,...,matched (3),matched (3),1075.5417,570.08691,947.3175,246.68668,matched (3),1285.0,2206.0,matched (3)
1,REM,AINTREE UNIVERSITY HOSPITAL NHS FOUNDATION TRUST,Lung,ALL CARE,9.0,6.0,3.0,3.0,0.0,2.0,...,matched (3),matched (3),1075.5417,570.08691,947.3175,246.68668,matched (3),1285.0,2206.0,matched (3)
2,REM,AINTREE UNIVERSITY HOSPITAL NHS FOUNDATION TRUST,Breast,ALL CARE,40.5,38.5,2.0,10.0,13.5,10.0,...,matched (3),matched (3),1075.5417,570.08691,947.3175,246.68668,matched (3),1285.0,2206.0,matched (3)
3,REM,AINTREE UNIVERSITY HOSPITAL NHS FOUNDATION TRUST,Lower Gastrointestinal,NON-ADMITTED,8.0,3.5,4.5,0.0,0.0,0.5,...,matched (3),matched (3),1075.5417,570.08691,947.3175,246.68668,matched (3),1285.0,2206.0,matched (3)
4,REM,AINTREE UNIVERSITY HOSPITAL NHS FOUNDATION TRUST,Lower Gastrointestinal,ADMITTED,13.5,8.0,5.5,1.0,0.0,1.0,...,matched (3),matched (3),1075.5417,570.08691,947.3175,246.68668,matched (3),1285.0,2206.0,matched (3)

In [8]:
data.keys()

Index(['ods_code', 'provider', 'cancer', 'care', 'total_trt', 'less62wt',
       'more62wt', 'wtgrp1', 'wtgrp2', 'wtgrp3', 'wtgrp4', 'wtgrp5', 'wtgrp6',
       'wtgrp7', 'wtgrp8', 'breachpercent', 'shmi_value', 'shmi_banding',
       'SHMI_merge', 'beds_day', 'bedDay_merge', 'beds_night',
       'bedNight_merge', '_Anaesthetics', '_Clinical_oncology',
       '_Emergency_Medicine', '_General_medicine_group', '_Pathology_group',
       '_Radiology_group', '_Surgical_group', 'hee_region_code', 'hee_regions',
       'grade_1', 'grade_2', 'grade_3', 'grade_4', 'grade_5', 'grade_6',
       'grade_7', 'grade_8', 'grade_9', 'grade_10', 'totstaff_merge',
       'medstaff_merge', '_Nurse_HealthVisitors', '_STT', '_Support_Clinical',
       '_Support_STT', 'nonmedstaff_merge', 'ytd_plan', 'ytd_actual',
       'finance_merge'],
      dtype='object')